spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
    open-in-view: false

  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration

  jwt:
    issuer: ${JWT_ISSUER}
    prefix: ${JWT_PREFIX}
    header: ${JWT_HEADER}
    secret-key: ${JWT_SECRET_KEY}
    access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
    refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true

  frontend:
    url: ${FRONTEND_URL}

  admin:
    key: ${ADMIN_KEY}

  jackson:
    time-zone: Asia/Seoul

  file:
    path: ${FILE_PATH}

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  discord:
    webhook:
      exception:
        url: ${DISCORD_WEBHOOK_EXCEPTION_URL}

management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: '*'
        include: health,info
    web:
      base-path: /actuator

  endpoint:
    health:
      enabled: true
    info:
      enabled: true