package com.solve.domain.problem.domain.enums

enum class ProblemTag {
    DYNAMIC_PROGRAMMING,
    MATHEMATICS,
    GREEDY,
    GRAPH_THEORY,
    GRAPH_TRAVERSAL,
    IMPLEMENTATION,
    DATA_STRUCTURES,
    STRING,
    GEOMETRY,
    SORTING,
    BINARY_SEARCH,
    DIVIDE_AND_CONQUER,
    BRUTEFORCE,
    BACKTRACKING,
    SIMULATION;
}